Feat - criar controller + route de convidados
Prime-events/Prime-events pull request #14
Opened 2024-10-14 23:45 UTC by gbrljlima

<h1> Criado controller + route de convidados </h1><br>

- Criei o controller e a rota, aparentemente funcionando normal no banco de dados. 
- Alterei o modelo de convidado para começar com a presença em false. Assim quando for criado o convidado não será necessário preencher a presença, apenas modificar posteriormente.<br>
- Também coloquei no index.js a linha <i>pool.sync(force:true)</i>, forçando as tabelas serem recriadas quando iniciar o servidor.

2024-10-15 17:16 UTC, UesleiLM requested changes
Favor, corrigir método atualizarConvidado, localizado em controller/ConvidadoController.js
Necessário adicionar o atributo "presenca" dentro do método atualizarConvidado.

2024-10-16 01:09 UTC, gbrljlima commented
> Favor, corrigir método atualizarConvidado, localizado em controller/ConvidadoController.js Necessário adicionar o atributo "presenca" dentro do método atualizarConvidado.

O método atualizarConvidado foi consertado.

2024-10-17 22:48 UTC, UesleiLM approved these changes
Fiz umas requisições de teste e funcionou corretamente, porém, você esqueceu de adicionar o código: app.use(convidadosRouter) no arquivo index.js. Irei aprovar essa PR, daí na próxima task que eu for fazer, irei adicionar isso.

2024-10-18 17:08 UTC, MaiconCesar79 approved these changes

2024-10-18 17:08 UTC, merged