Feat - Integracao componentes Inicio
Prime-events/Prime-events pull request #34
Opened 2024-11-09 00:49 UTC by gbrljlima

<h1> Integração dos componentes na página inicial do dashboard </h1>

- Componentes Header, SideBar, Cards e Calendario integrados.
- Feito alterações nas configurações do header para o nome e sobrenome serem alterados.

2024-11-09 14:31 UTC, MaiconCesar79 requested changes
na tela do mobile precisa alterar o css, ta modificando o container em vez do containerCriacao e isso ta fazendo com que o grid de cards fique colado na sidebar.

aqui o css do mobile para substituir:

media (max-width: 480px) {
    .containerCriacao {
        flex-direction: row; /* Mantém a direção em linha */
        width: auto;
    }
    .grid {
        flex: 1; /* Garante que a grid ocupe o restante do espaço disponível */
        flex-direction: column; /* Mantém os cards em linha */
        width: 100%; /* Garante que a grid ocupe toda a largura */
    }
    .card {
        flex: 0 0 80px; /* Cada card ocupa 80px de largura em telas menores */
        margin: 5px; /* Adiciona margem entre os cards */
    }
}

2024-11-09 17:06 UTC, gbrljlima commented
> na tela do mobile precisa alterar o css, ta modificando o container em vez do containerCriacao e isso ta fazendo com que o grid de cards fique colado na sidebar.
> 
> aqui o css do mobile para substituir:
> 
> media (max-width: 480px) { .containerCriacao { flex-direction: row; width: auto; } .grid { flex: 1; /* Garante que a grid ocupe o restante do espaço disponível _/ flex-direction: column; width: 100%; /_ Garante que a grid ocupe toda a largura _/ } .card { flex: 0 0 80px; /_ Cada card ocupa 80px de largura em telas menores _/ margin: 5px; /_ Adiciona margem entre os cards */ } }

Alterado!

2024-11-09 17:09 UTC, MaiconCesar79 approved these changes

2024-11-11 17:13 UTC, UesleiLM approved these changes

2024-11-11 17:13 UTC, merged